-- V1__init_schema.sql
-- Khởi tạo cấu trúc bảng cơ sở dữ liệu ban đầu cho hệ thống quản lý nhà thông minh

CREATE TABLE IF NOT EXISTS NguoiDung (
    MaNguoiDung INT AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    SoDienThoai VARCHAR(15),
    VaiTro VARCHAR(20) NOT NULL CHECK (VaiTro IN ('Admin', 'ThanhVien')),
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Nha (
    MaNha INT AUTO_INCREMENT PRIMARY KEY,
    TenNha VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(200),
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'ONha' CHECK (TrangThai IN ('ONha', 'VangNha')),
    MaNguoiDung INT NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Nha_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NguoiDung_Nha (
    MaNguoiDung INT NOT NULL,
    MaNha INT NOT NULL,
    NgayThamGia DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MaNguoiDung, MaNha),
    CONSTRAINT FK_NDN_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung),
    CONSTRAINT FK_NDN_Nha FOREIGN KEY (MaNha) REFERENCES Nha(MaNha)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Phong (
    MaPhong INT AUTO_INCREMENT PRIMARY KEY,
    TenPhong VARCHAR(100) NOT NULL,
    MaNha INT NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Phong_Nha FOREIGN KEY (MaNha) REFERENCES Nha(MaNha)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ThietBi (
    MaThietBi INT AUTO_INCREMENT PRIMARY KEY,
    TenThietBi VARCHAR(100) NOT NULL,
    LoaiThietBi VARCHAR(50) NOT NULL,
    MaPhong INT NOT NULL,
    TrangThai VARCHAR(10) NOT NULL DEFAULT 'Tat' CHECK (TrangThai IN ('Bat', 'Tat')),
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ThietBi_Phong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CamBien (
    MaCamBien INT AUTO_INCREMENT PRIMARY KEY,
    LoaiCamBien VARCHAR(50) NOT NULL CHECK (LoaiCamBien IN ('NhietDo', 'DoAm', 'ChuyenDong', 'Cua', 'Khoi', 'RoRiNuoc')),
    MaPhong INT NOT NULL,
    MaThietBi INT NULL,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CamBien_Phong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
    CONSTRAINT FK_CamBien_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LichSuCamBien (
    MaBanGhi BIGINT AUTO_INCREMENT PRIMARY KEY,
    MaCamBien INT NOT NULL,
    GiaTri FLOAT NOT NULL,
    ThoiGianGhiNhan DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSCB_CamBien FOREIGN KEY (MaCamBien) REFERENCES CamBien(MaCamBien)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS KichBan (
    MaKichBan INT AUTO_INCREMENT PRIMARY KEY,
    TenKichBan VARCHAR(100) NOT NULL,
    MaNha INT NOT NULL,
    MaNguoiDung INT NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_KichBan_Nha FOREIGN KEY (MaNha) REFERENCES Nha(MaNha),
    CONSTRAINT FK_KichBan_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS KichBan_HanhDong (
    MaHanhDong INT AUTO_INCREMENT PRIMARY KEY,
    MaKichBan INT NOT NULL,
    MaThietBi INT NOT NULL,
    HanhDong VARCHAR(20) NOT NULL,
    CONSTRAINT FK_KBHD_KichBan FOREIGN KEY (MaKichBan) REFERENCES KichBan(MaKichBan),
    CONSTRAINT FK_KBHD_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS QuyTacTuDong (
    MaQuyTac INT AUTO_INCREMENT PRIMARY KEY,
    TenQuyTac VARCHAR(100) NOT NULL,
    MaNha INT NOT NULL,
    MaCamBien INT NULL,
    LoaiDieuKien VARCHAR(50) NOT NULL,
    ToanTu VARCHAR(5) NULL,
    GiaTriNguong FLOAT NULL,
    MaThietBiHanhDong INT NOT NULL,
    HanhDong VARCHAR(20) NOT NULL,
    ThoiGianTre INT NULL,
    TrangThai TINYINT(1) NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_QTTD_Nha FOREIGN KEY (MaNha) REFERENCES Nha(MaNha),
    CONSTRAINT FK_QTTD_CamBien FOREIGN KEY (MaCamBien) REFERENCES CamBien(MaCamBien),
    CONSTRAINT FK_QTTD_ThietBi FOREIGN KEY (MaThietBiHanhDong) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LichHenGio (
    MaLich INT AUTO_INCREMENT PRIMARY KEY,
    MaThietBi INT NOT NULL,
    ThoiGian TIME NOT NULL,
    CacNgayLap VARCHAR(20) NOT NULL,
    HanhDong VARCHAR(20) NOT NULL,
    TrangThai TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT FK_LHG_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CanhBao (
    MaCanhBao INT AUTO_INCREMENT PRIMARY KEY,
    MaNha INT NOT NULL,
    LoaiCanhBao VARCHAR(50) NOT NULL,
    MaThietBi INT NULL,
    MaCamBien INT NULL,
    NoiDung VARCHAR(255) NOT NULL,
    ThoiGian DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DaDoc TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT FK_CanhBao_Nha FOREIGN KEY (MaNha) REFERENCES Nha(MaNha),
    CONSTRAINT FK_CanhBao_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi),
    CONSTRAINT FK_CanhBao_CamBien FOREIGN KEY (MaCamBien) REFERENCES CamBien(MaCamBien)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LichSuHoatDong (
    MaLichSu BIGINT AUTO_INCREMENT PRIMARY KEY,
    MaThietBi INT NOT NULL,
    MaNguoiDung INT NULL,
    HanhDong VARCHAR(20) NOT NULL,
    Nguon VARCHAR(20) NOT NULL CHECK (Nguon IN ('NguoiDung', 'TuDong', 'KichBan', 'LichHenGio')),
    ThoiGian DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSHD_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi),
    CONSTRAINT FK_LSHD_NguoiDung FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
) ENGINE=InnoDB;
